frase = input('Digite uma frase: ')
palavra_antiga = input('Da frase escolhida, informe uma palavra que deseja substituir: ')
palavra_nova = input('Agora informe uma palavra nova para substituir a anterior: ')

frase_alterada = frase.replace(palavra_antiga, palavra_nova)
print('\n')
print('Frase em letra maiúscula: ')
print(frase.upper())
print('\n')
print('Quantidade de caracteres na frase:')
print(len(frase))
print('\n')
print('Frase alterada: ')
print(frase_alterada)